# Generated by Django 5.1.6 on 2025-02-19 05:34

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OasisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrn', models.CharField(max_length=100)),
                ('pat_demo', models.TextField(blank=True, null=True)),
                ('cli_rec', models.TextField(blank=True, null=True)),
                ('bims', models.TextField(blank=True, null=True)),
                ('cams', models.TextField(blank=True, null=True)),
                ('phq', models.TextField(blank=True, null=True)),
                ('phy_ass', models.TextField(blank=True, null=True)),
                ('rom', models.TextField(blank=True, null=True)),
                ('spc_tre', models.TextField(blank=True, null=True)),
                ('ser_req', models.TextField(blank=True, null=True)),
                ('cli_sum', models.TextField(blank=True, null=True)),
                ('med_sup', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('GG0130A', models.TextField(blank=True, null=True)),
                ('GG0130B', models.TextField(blank=True, null=True)),
                ('GG0130C', models.TextField(blank=True, null=True)),
                ('GG0130E', models.TextField(blank=True, null=True)),
                ('GG0130F', models.TextField(blank=True, null=True)),
                ('GG0130G', models.TextField(blank=True, null=True)),
                ('GG0130H', models.TextField(blank=True, null=True)),
                ('GG0170AB', models.TextField(blank=True, null=True)),
                ('GG0170C', models.TextField(blank=True, null=True)),
                ('GG0170D', models.TextField(blank=True, null=True)),
                ('GG0170E', models.TextField(blank=True, null=True)),
                ('GG170F', models.TextField(blank=True, null=True)),
                ('GG170I', models.TextField(blank=True, null=True)),
                ('GG170J', models.TextField(blank=True, null=True)),
                ('GG170K', models.TextField(blank=True, null=True)),
                ('GG170L', models.TextField(blank=True, null=True)),
                ('GG170M', models.TextField(blank=True, null=True)),
                ('GG170N', models.TextField(blank=True, null=True)),
                ('GG170O', models.TextField(blank=True, null=True)),
                ('GG170P', models.TextField(blank=True, null=True)),
                ('GG170Q', models.TextField(blank=True, null=True)),
                ('GG170R', models.TextField(blank=True, null=True)),
                ('assisted_device', models.TextField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('cli_name', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mandatory_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concent_img', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('emg_img', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('med_list_img', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('add_doc_img1', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('add_doc_img2', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('misc_img', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('oasis_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_documents', to='home.oasisinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=home.models.image_upload_path)),
                ('img_des', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('oasis_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.oasisinfo')),
            ],
        ),
    ]
